version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'cqrs-mongodb'
    hostname: 'cqrs-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=user_articles
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./db-volume:/data/db
    ports:
    - '27017:27017'
    - '27019:27019'

